In [4]:
import random
import numpy as np
from tqdm.auto import tqdm

In [46]:
coefs = np.array([
    [1.02, 18],
#     [2.55, 1.55],
#     [5.2, 1.16],
#     [10.5, 1.05],
#     [1.35, 3.2],
    
#     [1.05, 16],
#     [1.45, 3.10]
])
num_games = len(coefs)

In [47]:
def get_coefs_distrib(coefs):
#     compl = 1 / coefs
    compl = coefs - coefs.sum(axis=1, keepdims=True)
    compl = compl / compl.sum(axis=1, keepdims=True)
    return compl

In [48]:
get_coefs_distrib(coefs)

array([[0.94637224, 0.05362776]])

In [49]:
def random_dna(num_games):
    dna = np.random.rand(num_games, 2)
    return dna / dna.sum()

In [50]:
dna = random_dna(num_games)
dna

array([[0.78903851, 0.21096149]])

In [51]:
def fitness(coefs, dna):
    coefs_distrib = get_coefs_distrib(coefs)
    out1 = (dna[:,0] * coefs[:,0] - dna[:,1]) * coefs_distrib[:,0]
    out2 = (dna[:,1] * coefs[:,1] - dna[:,0]) * coefs_distrib[:,1]
    return sum(out1 + out2)

In [52]:
dna = random_dna(len(coefs))
f = fitness(coefs, dna)

best_fitnes = -float('inf')
best_dna = None

for _ in tqdm(range(100_000)):
    dna = random_dna(len(coefs))
    f = fitness(coefs, dna)
    if f > best_fitnes:
        best_fitnes = f
        best_dna = dna
best_fitnes

  0%|          | 0/100000 [00:00<?, ?it/s]

0.9116672523523008

In [29]:
best_dna * 100

array([[27.24821717,  1.50445729],
       [ 0.46484299,  1.15257994],
       [67.55589627,  2.07400634]])

In [30]:
coefs

array([[ 1.02, 18.  ],
       [ 5.2 ,  1.16],
       [ 1.05, 16.  ]])