In [17]:
import random
import numpy as np

In [336]:
coefs = np.array([
    [1.02, 18],
    [2.55, 1.55],
    [5.2, 1.16],
    [10.5, 1.05],
    [1.35, 3.2],
])
num_games = len(coefs)

In [337]:
def get_coefs_distrib(coefs):
    compl = 1 / coefs
#     compl = coefs - coefs.sum(axis=1, keepdims=True)
#     compl = compl / compl.sum(axis=1, keepdims=True)
    return compl

In [338]:
get_coefs_distrib(coefs)

array([[0.98039216, 0.05555556],
       [0.39215686, 0.64516129],
       [0.19230769, 0.86206897],
       [0.0952381 , 0.95238095],
       [0.74074074, 0.3125    ]])

In [339]:
def random_dna(num_games):
    return np.random.rand(num_games, 2)

In [340]:
dna = random_dna(num_games)
dna

array([[0.30033113, 0.62649843],
       [0.65219119, 0.1959825 ],
       [0.96728431, 0.1053905 ],
       [0.99497864, 0.79988691],
       [0.89480463, 0.99345062]])

In [341]:
dna / dna.sum()

array([[0.04598689, 0.09592983],
       [0.09986392, 0.03000896],
       [0.14811118, 0.01613746],
       [0.15235175, 0.12247918],
       [0.13701304, 0.15211778]])

In [342]:
dna[:,0]

array([0.30033113, 0.65219119, 0.96728431, 0.99497864, 0.89480463])

In [343]:
def fitness(coefs, dna):
    coefs_distrib = get_coefs_distrib(coefs)
    norm_dna = dna / dna.sum() # * C
    out1 = (dna[:,0] * coefs[:,0] - dna[:,1]) * coefs_distrib[:,0]
    out2 = (dna[:,1] * coefs[:,1] - dna[:,0]) * coefs_distrib[:,1]
    return sum(out1 + out2)

In [344]:
coefs

array([[ 1.02, 18.  ],
       [ 2.55,  1.55],
       [ 5.2 ,  1.16],
       [10.5 ,  1.05],
       [ 1.35,  3.2 ]])

In [347]:
dna = random_dna(len(coefs))
f = fitness(coefs, dna)

best_fitnes = -1
best_dna = None

for _ in range(50000):
    dna = random_dna(len(coefs))
    f =    
    if f > best_fitnes:
        best_fitnes = f
        best_dna = dna
f

3.346852287591129

In [364]:
dna / dna.sum() * 100

array([[14.43006915,  6.70266882],
       [12.83906151,  0.92683065],
       [ 7.20511502, 15.43470553],
       [ 8.79461814, 10.68531792],
       [11.37637095, 11.60524231]])

In [365]:
coefs

array([[ 1.02, 18.  ],
       [ 2.55,  1.55],
       [ 5.2 ,  1.16],
       [10.5 ,  1.05],
       [ 1.35,  3.2 ]])