In [4]:
import torch
import torch.nn as nn
import torchvision

import numpy as np
import matplotlib.pyplot as plt

In [5]:
torch.__version__

'1.6.0'

# Quick torch primer

## We can have tensors
Tensors are containers for numbers.

**single number**

In [18]:
t = torch.tensor(77)
t, t.shape

(tensor(77), torch.Size([]))

**list of numbers also known as vectors**

In [19]:
t = torch.tensor([1, 4, 10])
t, t.shape

(tensor([ 1,  4, 10]), torch.Size([3]))

**list of list of numbers a.k.a. matrix**

In [20]:
t = torch.tensor([
    [1, 2, 3],
    [5, 6, 7],
    [9, 8, 7],
])
t, t.shape

(tensor([[1, 2, 3],
         [5, 6, 7],
         [9, 8, 7]]), torch.Size([3, 3]))

**mind you they have to be padded to the same length**

In [12]:
try:
    torch.tensor([
        [1, 2, 3],
        [2, 3]
    ])
except ValueError:
    print('this does not work')

this does not work


**list of matrices, a.k.a. 3D tensors (image)**

In [21]:
t = torch.tensor([
    [[1, 2],
     [3, 4]],
    [[6, 9],
     [8, 8]],
    [[3, 2],
     [3, 4]]
])
t, t.shape

(tensor([[[1, 2],
          [3, 4]],
 
         [[6, 9],
          [8, 8]],
 
         [[3, 2],
          [3, 4]]]), torch.Size([3, 2, 2]))

**n-dim tensors**

In [28]:
# batch, of sequence of 3 channel images of size 32x32, a.k.a. 8 videos
t = torch.rand(8, 20, 3, 32, 32)
t.shape

torch.Size([8, 20, 3, 32, 32])

In [27]:
# t

## We can manipulate tensors

In [ ]:
t = torch.rand(8, 20, 3, 32, 32)